kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgresql
  labels:
    deployment: postgresql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-storage
  volumeMode: Filesystem