apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: secret-of-life
  namespace: sealed-secrets
spec:
  encryptedData:
    secret: AgAgaazmve+X+V/Dk/39z8rWbIPjwFZDI6vWE8W0gHGtgSesfGHOwh9BDiTNY8xRBqzahM3rPiCwkE0iYpAWup0K+wQ6y0n/Ku9DsBPeVUGYbmF9X70nI+rI5O7tk/hNNC2MCGvGGCAXIiGM452tye+tzdMIyI84CZHA5Tne5Aw1seGgHNTdqRKdwGWwT1EnzkwK+gznizxzGlvv/bn9bxKid6L4srcd5aW9ju+HBqqxZwG+YJy0ZHsKHxuzpMAOgz5RT6dpC2y2zYffpyIRtKwVFkqXxO0Obz4Nl1+/kR8e9TyIzjor52UngCS9QpcukwF0bMznpYcBoP+dAx0fvcW+nBD0AQk276zFOJD6LcuXzlkelaBYJV/45eDgJ4nk4hA15xij8RoAln/JJM6oEaMoFmIEmQkztuB9GadISjn8bwdOkKLn632RO8SZ0ObFS8t/igWPueiJ0qoKdNUv8ZgrXxh1xEJIuViiVnfyLw/hLQENTG8ntbCbWrDD+e36mLJGQE1/wCx4OoJKMlx8nbTReyA6pUjICO9wm9k2Hx4CSSw4jN+cA21aJLBrAxTX48H0L5s2UnmRCp95mUVUEcE/QtWjeRfcq+o4UUbDRQQfhIQc3L6nP6e/UPEMhozRrYxslJafct/DSxRZpscM9qvVGJqyF6yu1DxPStPAj5Er3xJ/1FTNQFnohWSRnoGdWw/RjA==
  template:
    metadata:
      creationTimestamp: null
      name: secret-of-life
      namespace: sealed-secrets
    type: Opaque

